name: Simulate

on: [push, pull_request]  # Trigger the workflow on push events

jobs:
  run-command:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - name: Run command with timeout
        run: |
          timeout 10s bash -c "./gradlew simulateJava > command-output.log 2>&1"
          echo "Command completed or timed out."

      - name: Check for errors
        if: ${{ failure() }}
        run: |
          cat command-output.log
          echo "Command failed."
          exit 1  # Explicitly fail the step

      - name: Mark step as successful
        if: ${{ success() }}
        run: |
          echo "Command ran successfully for 10 seconds or completed earlier."
          exit 0  # Explicitly mark the step as successful
