name: Simulate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission # just in case
        run: chmod +x gradlew
      - name: Compile robot code
        run: ./gradlew build
      - name: Run WPILib simulation
        id: simulation
        run: |
          trap 'exit_code=$?; if [ $exit_code -eq 124 ]; then exit 0; else exit $exit_code; fi' EXIT
          timeout 10s ./gradlew simulateJava