name: Simulate

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        container: wpilib/roborio-cross-ubuntu:2024-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Grant execute permission # just in case
              run: chmod +x gradlew
            - name: Compile robot code
              run: ./gradlew build
            - name: Run WPILib simulation
              id: simulation
              run: |
                timeout 30s ./gradlew simulateJava; exit_code=$?
                if [ $exit_code -eq 124 ]; then
                  echo "The command timed out"
                elif [ $exit_code -ne 0 ]; then
                  echo "The command failed"
                fi
                echo "::set-output name=exit_code::$exit_code"
            - name: Check simulation result
              run: exit ${{ steps.simulation.outputs.exit_code }}
              if: ${{ steps.simulation.outputs.exit_code != '0' && steps.simulation.outputs.exit_code != '124' }}
