name: Simulate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission # just in case
        run: chmod +x gradlew
      - name: Compile robot code
        run: ./gradlew build
      - name: Run WPILib simulation
        id: simulation
        run: |
          timeout 10s ./gradlew simulateJava
          exit_code=$?
          if [ $exit_code -eq 124 ]; then
            echo "The command ran for at least 10 seconds (success)"
            exit 0
          else
            echo "The command ended before 10 seconds (failure)"
            exit 1  # Exit with a failure code
          fi