name: Simulate

on: [push, pull_request]  # Trigger the workflow on push events

jobs:
  run-command:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:

      - uses: actions/checkout@v4
      - name: Grant execute permission # just in case
        run: chmod +x gradlew

      - name: Run Gradle build with timeout
        timeout-minutes: 1  # Set a timeout for the entire step
        run: |
          timeout 10s ./gradlew build || exit 0  # Run build for 10 seconds or until error

          # If the timeout is reached, mark the step as successful
          echo "Gradle build timed out after 10 seconds, but marking as successful"
          exit 0
